/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as QuizQuizTypeImport } from './routes/quiz.$quizType'
import { Route as CoursesCoursesNameImport } from './routes/courses.$coursesName'

// Create Virtual Routes

const RoadmapLazyImport = createFileRoute('/roadmap')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const RoadmapLazyRoute = RoadmapLazyImport.update({
  path: '/roadmap',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/roadmap.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const QuizQuizTypeRoute = QuizQuizTypeImport.update({
  path: '/quiz/$quizType',
  getParentRoute: () => rootRoute,
} as any)

const CoursesCoursesNameRoute = CoursesCoursesNameImport.update({
  path: '/courses/$coursesName',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/roadmap': {
      preLoaderRoute: typeof RoadmapLazyImport
      parentRoute: typeof rootRoute
    }
    '/courses/$coursesName': {
      preLoaderRoute: typeof CoursesCoursesNameImport
      parentRoute: typeof rootRoute
    }
    '/quiz/$quizType': {
      preLoaderRoute: typeof QuizQuizTypeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  RoadmapLazyRoute,
  CoursesCoursesNameRoute,
  QuizQuizTypeRoute,
])

/* prettier-ignore-end */
